import { QueryCommand, UpdateCommand } from "@aws-sdk/lib-dynamodb";
import { ddb } from "./shared/dynamo.js";
import {
  BedrockRuntimeClient,
  ConverseCommand,
} from "@aws-sdk/client-bedrock-runtime";
import { PollyClient, SynthesizeSpeechCommand } from "@aws-sdk/client-polly";
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";

const bedrock = new BedrockRuntimeClient({});
const polly = new PollyClient({});
const s3 = new S3Client({});

const generateAISummary = async (paper) => {
  const prompt = `Summarize this AI paper in 3-4 simple sentences:

Title: ${paper.title}
Topic: ${paper.topic}
Abstract: ${paper.summary}`;

  const response = await bedrock.send(
    new ConverseCommand({
      modelId: process.env.BEDROCK_MODEL_ID,
      messages: [{ role: "user", content: [{ text: prompt }] }],
      inferenceConfig: { maxTokens: 300, temperature: 0.5 },
    })
  );

  return response.output.message.content[0].text.trim();
};

const generateAudio = async (text) => {
  const response = await polly.send(
    new SynthesizeSpeechCommand({
      Text: text,
      OutputFormat: "mp3",
      VoiceId: "Joanna",
      Engine: "neural",
    })
  );

  const chunks = [];
  for await (const chunk of response.AudioStream) {
    chunks.push(chunk);
  }
  return Buffer.concat(chunks);
};

const uploadToS3 = async (buffer, externalId) => {
  const safeId = externalId.replace(/[^a-zA-Z0-9._-]/g, "_");
  const key = `audio/${safeId}.mp3`;

  await s3.send(
    new PutObjectCommand({
      Bucket: process.env.S3_BUCKET,
      Key: key,
      Body: buffer,
      ContentType: "audio/mpeg",
    })
  );

  return key;
};

const findUnprocessedPapers = async (topic, limit) => {
  const response = await ddb.send(
    new QueryCommand({
      TableName: process.env.PAPERS_TABLE,
      IndexName: "topic-createdAt-index",
      KeyConditionExpression: "#t = :t",
      FilterExpression: "attribute_not_exists(audioKey)",
      ExpressionAttributeNames: { "#t": "topic" },
      ExpressionAttributeValues: { ":t": topic },
      ScanIndexForward: false,
      Limit: Math.max(limit * 3, 30),
    })
  );

  return (response.Items ?? []).slice(0, limit);
};

export const handler = async (event, context) => {
  context.callbackWaitsForEmptyEventLoop = false;

  for (const record of event.Records) {
    const message = JSON.parse(record.body);
    const papers = await findUnprocessedPapers(
      message.topic,
      message.insertedCount || 10
    );

    for (const paper of papers) {
      if (paper.audioKey) continue;

      // plainLanguageSummary — 3-4 sentence simplified version generated by the LLM (Bedrock/Ollama), plain English for non-specialists
      const plainLanguageSummary = await generateAISummary(paper);
      const audio = await generateAudio(plainLanguageSummary);
      const audioKey = await uploadToS3(audio, paper.externalId);

      await ddb.send(
        new UpdateCommand({
          TableName: process.env.PAPERS_TABLE,
          Key: { externalId: paper.externalId },
          UpdateExpression: "SET plainLanguageSummary = :s, audioKey = :u",
          ExpressionAttributeValues: {
            ":s": plainLanguageSummary,
            ":u": audioKey,
          },
        })
      );
    }
  }

  return {};
};
